server:
   port: 8082
   context-path: /account
   
   
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres  
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver  
    application:
      name: account-service


logging:  
  level:   
    org.business.system.account.mapper: debug
      

    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

   
