server:
   port: 8081
   context-path: /notice
   
   
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres  
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver  
    application:
      name: notice-service
      
      
logging:  
  level:   
    org.business.system.notice.mapper: debug
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
      
spring:
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

   
