server:
   port: 8081
   context-path: /notice
   
   
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres  
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver  
      
      
logging:  
  level:   
    org.business.system.notice.mapper: debug

   
