server:
   port: 8084
   context-path: /newstart
   
   
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres  
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver  
    application:
      name: newstart-service
      
      
logging:  
  level:   
    org.business.system.newstart.mapper: debug
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

   
