server:
   port: 8086
   context-path: /member
   
   
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres  
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver  
    application:
      name: member-service

      
      
logging:  
  level:   
    org.business.system.activity.mapper: debug


    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
      

      



   
